### ISSUE TITLE
inconsistency between F measure generated by provided code and official matlab code

### ISSUE THREAD

**Issue by chenz97** [WenjunHui1/TSP-SAM#4]
Dear authors, 

thank you for your work and releasing the code. 

I have tried evaluation using the provided code. I find that by default the F measure is computed but not reported. After I print the output, I find the printed F-measure is different from (actually higher than) the results obtained by the official matlab code. Is there any modifications to made the resolve the inconsistency? 

Thank you.

**Comment by chenz97** [comment]
Note that I do find beta is different in that by default the official code uses beta2=1 while your code uses beta2=0.3. However, the figures are still different (the difference becomes even larger) after setting beta2=1 in your code.

**Comment by WenjunHui1** [comment]
> Dear authors,
> 
> thank you for your work and releasing the code.
> 
> I have tried evaluation using the provided code. I find that by default the F measure is computed but not reported. After I print the output, I find the printed F-measure is different from (actually higher than) the results obtained by the official matlab code. Is there any modifications to made the resolve the inconsistency?
> 
> Thank you.



The results reported in the paper are evaluated by the matlab code.

**Comment by chenz97** [comment]
Thank you for the response.
